// Reads .env.local and generates config.js, which the HTML pages load
// via <script src="config.js"> before they call supabase.createClient().
//
// Run this any time you change .env.local:
//   npm run build:config
//
// config.js is gitignored — it's regenerated from .env.local, never committed.

const fs = require('fs');
const path = require('path');

const ENV_PATH = path.join(__dirname, '..', '.env.local');
const OUTPUT_PATH = path.join(__dirname, '..', 'config.js');

function loadEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};

  const env = {};
  const lines = fs.readFileSync(filePath, 'utf8').split('\n');

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;

    const eqIndex = line.indexOf('=');
    if (eqIndex === -1) continue;

    const key = line.slice(0, eqIndex).trim();
    let value = line.slice(eqIndex + 1).trim();

    // Strip matching surrounding quotes, if present.
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    env[key] = value;
  }

  return env;
}

// Local dev: values come from .env.local.
// Vercel (or any CI): values come from process.env, set in the dashboard —
// there's no .env.local file present there since it's gitignored.
// process.env wins if both are present.
const fileEnv = loadEnvFile(ENV_PATH);
const env = {
  SUPABASE_URL: process.env.SUPABASE_URL || fileEnv.SUPABASE_URL,
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || fileEnv.SUPABASE_ANON_KEY,
  // Firebase Cloud Messaging (push notifications) — all safe to expose
  // client-side, they only identify which Firebase project to talk to.
  FIREBASE_API_KEY: process.env.FIREBASE_API_KEY || fileEnv.FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN || fileEnv.FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID || fileEnv.FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET || fileEnv.FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID || fileEnv.FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID: process.env.FIREBASE_APP_ID || fileEnv.FIREBASE_APP_ID,
  FIREBASE_VAPID_KEY: process.env.FIREBASE_VAPID_KEY || fileEnv.FIREBASE_VAPID_KEY,
};

// Only Supabase is required to build at all — Firebase is optional so the
// site still works before push notifications are set up. If any Firebase
// var is missing, we just skip emitting FIREBASE_CONFIG and warn instead
// of failing the whole build.
const required = ['SUPABASE_URL', 'SUPABASE_ANON_KEY'];
const missing = required.filter((key) => !env[key]);
if (missing.length) {
  console.error(
    `Missing required env vars: ${missing.join(', ')}. ` +
    `Set them in .env.local for local dev, or in your host's environment variables dashboard for deployment.`
  );
  process.exit(1);
}

const firebaseKeys = [
  'FIREBASE_API_KEY', 'FIREBASE_AUTH_DOMAIN', 'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET', 'FIREBASE_MESSAGING_SENDER_ID', 'FIREBASE_APP_ID', 'FIREBASE_VAPID_KEY',
];
const firebaseConfigured = firebaseKeys.every((key) => env[key]);
if (!firebaseConfigured) {
  console.warn('Firebase env vars not fully set — push notifications will stay disabled until they are. (This is fine if you haven\'t set up Firebase yet.)');
}

// NOTE: uses `self.X = ...` rather than `window.X = ...` so this same file
// works both when loaded by a normal page (self === window there) AND when
// imported by firebase-messaging-sw.js, which runs in a service worker with
// no `window` object at all.
const output = `// AUTO-GENERATED by scripts/build-config.js — do not edit by hand.
// Values come from .env.local. Re-run "npm run build:config" after changing it.
self.SUPABASE_URL = ${JSON.stringify(env.SUPABASE_URL)};
self.SUPABASE_ANON_KEY = ${JSON.stringify(env.SUPABASE_ANON_KEY)};
self.FIREBASE_CONFIG = ${firebaseConfigured ? JSON.stringify({
  apiKey: env.FIREBASE_API_KEY,
  authDomain: env.FIREBASE_AUTH_DOMAIN,
  projectId: env.FIREBASE_PROJECT_ID,
  storageBucket: env.FIREBASE_STORAGE_BUCKET,
  messagingSenderId: env.FIREBASE_MESSAGING_SENDER_ID,
  appId: env.FIREBASE_APP_ID,
}) : 'null'};
self.FIREBASE_VAPID_KEY = ${JSON.stringify(env.FIREBASE_VAPID_KEY || null)};
`;

fs.writeFileSync(OUTPUT_PATH, output);
console.log(`Wrote ${OUTPUT_PATH}`);