// Reads .env.local and generates config.js, which the HTML pages load
// via <script src="config.js"> before they call supabase.createClient().
//
// Run this any time you change .env.local:
//   npm run build:config
//
// config.js is gitignored — it's regenerated from .env.local, never committed.

const fs = require('fs');
const path = require('path');

const ENV_PATH = path.join(__dirname, '..', '.env.local');
const OUTPUT_PATH = path.join(__dirname, '..', 'config.js');

function loadEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};

  const env = {};
  const lines = fs.readFileSync(filePath, 'utf8').split('\n');

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;

    const eqIndex = line.indexOf('=');
    if (eqIndex === -1) continue;

    const key = line.slice(0, eqIndex).trim();
    let value = line.slice(eqIndex + 1).trim();

    // Strip matching surrounding quotes, if present.
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    env[key] = value;
  }

  return env;
}

// Local dev: values come from .env.local.
// Vercel (or any CI): values come from process.env, set in the dashboard —
// there's no .env.local file present there since it's gitignored.
// process.env wins if both are present.
const fileEnv = loadEnvFile(ENV_PATH);
const env = {
  SUPABASE_URL: process.env.SUPABASE_URL || fileEnv.SUPABASE_URL,
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || fileEnv.SUPABASE_ANON_KEY,
};

const required = ['SUPABASE_URL', 'SUPABASE_ANON_KEY'];
const missing = required.filter((key) => !env[key]);
if (missing.length) {
  console.error(
    `Missing required env vars: ${missing.join(', ')}. ` +
    `Set them in .env.local for local dev, or in your host's environment variables dashboard for deployment.`
  );
  process.exit(1);
}

const output = `// AUTO-GENERATED by scripts/build-config.js — do not edit by hand.
// Values come from .env.local. Re-run "npm run build:config" after changing it.
window.SUPABASE_URL = ${JSON.stringify(env.SUPABASE_URL)};
window.SUPABASE_ANON_KEY = ${JSON.stringify(env.SUPABASE_ANON_KEY)};
`;

fs.writeFileSync(OUTPUT_PATH, output);
console.log(`Wrote ${OUTPUT_PATH}`);